import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./reset.scss";
const RobotoSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const RobotoMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Roulette",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoSans.variable} ${RobotoMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
